POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "hi",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "I don't have important attribute"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Update me",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "I have a user id",
    "important": true,
    "userId": "6434ad5414052b2656767635"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0MzRhZDU0MTQwNTJiMjY1Njc2NzYzNSIsImlhdCI6MTY4MTE3NzkzMH0.wf8y4GeeEhBNB9NzzylSVZkosc9J6atVsWjZ8e1klhQ

{
    "content": "I have a user id",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer 123

{
    "content": "I have a user id",
    "important": true
}